PROGRAM-ID: Walkthrough_Main**)
DISPLAY "Welcome%20to%20the%20Starforge%20and%20RAS-COBOL%20macro%20scripting%20language%20tutorial%20and%20documentation%20program."**)

COMMENT DISPLAY "First,%20let's%20begin%20with%20logging%20things%20to%20the%20console."**)
COMMENT WAIT 2**)
COMMENT DISPLAY "Let's%20log%20'Hello,%20World!'%20to%20the%20console!"**)
COMMENT DISPLAY "We%20will%20use%20the%20following%20syntax:"**)
COMMENT DISPLAY "DISPLAY Hello,%20World!**-)"**)
COMMENT WAIT 2**)
COMMENT DISPLAY ""**)

DISPLAY "1:%20Go%20over%20displaying%20and%20logging"**)
DISPLAY "2:%20Go%20over%20variables"**)
DISPLAY "3:%20Go%20over%20inputs%20and%20input%20variables"**)
DISPLAY "4:%20Go%20over%20comments"**)
DISPLAY "5:%20Go%20over%20setting%20temperature%20and%20pressure"**)
DISPLAY "6:%20Go%20over%20setting%20maximum%20and%20minimum%20rates"**)
DISPLAY "7:%20Go%20over%20calling%20other%20macros"**)

INPUT_VAR USER_NUM_INPUT "Please choose a number: "**)

MATH_DIVISION**)
IF |cond|_vUSER_NUM_INPUT EQUALS 1|cond| THEN CALL RAS_COBOL display_and_logging**)
IF |cond|_vUSER_NUM_INPUT EQUALS 2|cond| THEN CALL RAS_COBOL variables**)
IF |cond|_vUSER_NUM_INPUT EQUALS 3|cond| THEN CALL RAS_COBOL inputs_and_input_var**)
IF |cond|_vUSER_NUM_INPUT EQUALS 4|cond| THEN CALL RAS_COBOL comments**)
IF |cond|_vUSER_NUM_INPUT EQUALS 5|cond| THEN CALL RAS_COBOL temperature_and_pressure**)
IF |cond|_vUSER_NUM_INPUT EQUALS 6|cond| THEN CALL RAS_COBOL min_max_rates**)
IF |cond|_vUSER_NUM_INPUT EQUALS 7|cond| THEN CALL RAS_COBOL calling_macros**)
ELSE CALL RAS_COBOL walkthrough_err_return**)
REPEAT**)