PROGRAM-ID: variables
DISPLAY "There%20are%20two%20types%20of%20variables:%20Input%20variables,%20and%20Normal%20variables."**)
DISPLAY "To use regular variables, you must type out the following command:"**)
DISPLAY "VAR X Hello%-20there**-)"**)
DISPLAY "In the above example, we are assigning the value Hello%20there to the variable X."**)
DISPLAY "Because all StarForge/RAS-Cobol variables are essentially global variables, we can"**)
DISPLAY "call it from essentially anywhere, an example being:"**)
DISPLAY "DISPLAY%20_vX**-)"**)
DISPLAY "In the above example, we are indicating a variable by putting _v before our variable name."**)
DISPLAY "This outputs:"**)
DISPLAY "Hello%20there"**)
DISPLAY ----------------------------------------------------------------------------------------------**)
DISPLAY "Now,%20onto%20input%20variables."**)
DISPLAY "To%20define%20an%20input%20variable,%20you%20must%20type%20out%20the%20following%20command:"**)
DISPLAY "INPUT_VAR Y What is your name?:%20**-)"**)
DISPLAY "Input variables don't store anything until the user gives them a value. The above code would output:"**)
DISPLAY "What is your name?:%20"**)
DISPLAY "Let's%20assume%20that%20the%20user%20enters%20a%20name."**)
DISPLAY "What%20is%20your%20name?:%20Obi-Wan%20Kenobi"**)
DISPLAY "Now%20the%20value%20of%20our%20input%20variable,%20Y,%20is%20set%20to%20'Obi-Wan%20Kenobi'."**)
DISPLAY "Like%20before%20with%20regular%20variables,%20we%20can%20call%20it%20from%20essentially%20anywhere%20like%20this:"**)
DISPLAY "DISPLAY%20_vY**-)"**)
DISPLAY "This%20outputs:"**)
DISPLAY "Obi-Wan%20Kenobi"**)
DISPLAY ----------------------------------------------------------------------------------------------**)
WAIT 5**)
CALL RAS_COBOL macro_walkthrough_main**)